### ISSUE TITLE
TableData fetching: Include All Columns

### ISSUE THREAD

**Issue by nbrugger-tgm** [Local-Admin-BurgerKing/rest-api#9]
## Problem
At the moment it is not possible to get the value of a formula at a certain date / get all columns of a daily report (not only the one that hold data `daily-column`). This leads to a very uncomfortable use of the api and needs to be fixed
## Solve
Add a attribute to each point where you obtain a daily Report (also applys to #8 ) that all columns  are returned.

**Comment by Tbswss** [comment]
Added query parameter all_columns to all required TablesAPI-paths.

**Comment by nbrugger-tgm** [comment]
## Reopen
Due this change is done, certain flaws in the Manager classes appeared which.
The flag wont work until this issues are resolved/fixed.

#### Todo
There need to be a possibility to:
- Get a complete Report with 1 SQL Request
- Get many complete reports in a range of dates with one (or maximum `n` (number of reports)) SQL Request (s)
- Obtain the Sum (refering to #8 ) for a range with 1 SQL Call
- Obtain the sum from allready fetched full reports without an SQL Call

**Comment by nbrugger-tgm** [comment]
## Done
The database and core now supports this functionality
